application: githubanywhere
version: v0
runtime: python
api_version: 1

handlers:
- url: /xdr.html
  static_files: html/xdr.html
  upload: html/xdr.html

- url: /callback.html
  static_files: html/callback.html
  upload: html/callback.html

- url: /github-anywhere.js
  static_files: javascript/github-anywhere.js
  upload: javascript/github-anywhere.js

- url: /javascript
  static_dir: javascript

- url: /images
  static_dir: images

- url: /style
  static_dir: style

- url: /user/.*
  script: main.py

- url: /repos/.*
  script: main.py

- url: /login/.*
  script: main.py

- url: .*
  static_files: html/index.html
  upload: html/index.html