application: githubanywhere
version: dev
runtime: python
api_version: 1

handlers:
- url: /xdr.html
  static_files: html/xdr.html
  upload: html/xdr.html
  secure: always

- url: /callback.html
  static_files: html/callback.html
  upload: html/callback.html
  secure: always

- url: /github-anywhere.js
  static_files: javascript/github-anywhere.js
  upload: javascript/github-anywhere.js
  secure: always

- url: /javascript
  static_dir: javascript
  secure: always

- url: /images
  static_dir: images
  secure: always

- url: /style
  static_dir: style
  secure: always

- url: /user/.*
  script: main.py
  secure: always

- url: /repos/.*
  script: main.py
  secure: always

- url: /login/.*
  script: main.py
  secure: always

- url: .*
  static_files: html/index.html
  upload: html/index.html
  secure: always
